theme = "catppuccin"

repeat = "One"

shuffle = true

provider = "tidal"

[tidal]
enabled = true
quality = "lossless"

[ytmusic]
enabled = true
cookies_from = "vivaldi+gnomekeyring:/home/brozi/.config/vivaldi/Default"
