terminal_emulator = "kitty"

[hosts.default]
dpi = 96
rofi_font_size = 10
rofi_icon_size = "24px"
rofi_font_size_alt = 12
has_touchpad = false
has_numpad = true
monitor_count = 1

[hosts."brozi-laptop"]
dpi = 120
rofi_font_size = 10
rofi_icon_size = "34px"
rofi_font_size_alt = 15
has_touchpad = true
touchpad_name = "SYNA32F3:00 06CB:CFC5 Touchpad"
has_numpad = false
monitor_count = 1


[hosts."brozi-desktop"]
dpi = 96
rofi_icon_size = "24px"
rofi_font_size = 10
rofi_font_size_alt = 12
has_touchpad = false
has_numpad = true
monitor_count = 2
