#!/bin/sh

apt_updates=$(apt list --upgradable 2>/dev/null | grep -i upgradable)
apt_updates_num=$(echo "$apt_updates" | grep -c -v "^$")

if [ "$apt_updates_num" -gt 0 ]; then
  echo "$apt_updates"
fi
