#!/bin/sh

apt_updates=$(mintupdate-cli list 2>/dev/null)
flatpak_updates=$(flatpak remote-ls --updates 2>/dev/null)
apt_updates_num=$(echo "$apt_updates" | grep -c -v "^$")
flatpak_updates_num=$(echo "$flatpak_updates" | grep -c -v "^$")

if [ $((apt_updates_num + flatpak_updates_num)) -gt 0 ]; then

  if [ "$apt_updates_num" -gt 0 ]; then
    echo "$apt_updates"
  fi

  if [ "$flatpak_updates_num" -gt 0 ]; then
    echo "$flatpak_updates"
  fi

  # else
  # echo ""
fi
