-- return {
--   "chrisgrieser/nvim-spider",
--   opts = {},
--   keys = {
--     {
--       "w",
--       "<cmd>lua require('spider').motion('w')<CR>",
--       mode = { "n", "o", "x" },
--       desc = "Move to start of the next word",
--     },
--     {
--       "e",
--       "<cmd>lua require('spider').motion('e')<CR>",
--       mode = { "n", "o", "x" },
--       desc = "Move to the end of the word",
--     },
--     {
--       "b",
--       "<cmd>lua require('spider').motion('b')<CR>",
--       mode = { "n", "o", "x" },
--       desc = "Move to the start of the previous word",
--     },
--   },
-- }
