# Switch to workspace

bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5

bindsym $mod+Mod1+1 workspace $ws6
bindsym $mod+Mod1+2 workspace $ws7
bindsym $mod+Mod1+3 workspace $ws8
bindsym $mod+Mod1+4 workspace $ws9
bindsym $mod+Mod1+5 workspace $ws10

# Move focused container to workspace on the main monitor

bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5

bindsym $mod+Shift+Mod1+1 move container to workspace $ws6
bindsym $mod+Shift+Mod1+2 move container to workspace $ws7
bindsym $mod+Shift+Mod1+3 move container to workspace $ws8
bindsym $mod+Shift+Mod1+4 move container to workspace $ws9
bindsym $mod+Shift+Mod1+5 move container to workspace $ws10

