# hot reload config
unbind r 
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"
# Change prefix from 'Ctrl+b' to 'Ctrl+a'
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix

set -g @plugin "catppuccin/tmux"
set -g @plugin "christoomey/vim-tmux-navigator"
run 'tpack init'
