# hot reload config
unbind r 
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"
# Change prefix from 'Ctrl+b' to 'Ctrl+a'
unbind C-b
set-option -g prefix C-s
bind-key C-s send-prefix
# turn on mouse support
set -g mouse on
set -g default-terminal "tmux-256color"
# set status interval for the bar to update
set -g status-interval 1

bind-key h select-pane -L 
bind-key j select-pane -D 
bind-key k select-pane -U 
bind-key l select-pane -R 

set-option -g status-position top

# Plugin list

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"


# set the directory module to display full path
set -g @catppuccin_directory_text " #{pane_current_path}"

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_session}"

# remove hostname from the window bar
set -g @catppuccin_window_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_pane_number_position "right"
set -g @catppuccin_window_number_position "right"

# load vim-tmux-navigator plugin
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin "catppuccin/tmux"

# Init TMUX plugin manager
run 'tpack init'
